data:
  inp: "./../inp"
  out: "./../out"
  labelmaps:
    id2label: {0: "NOT", 1: "HOF"}
    label2id: {"NOT": 0, "HOF": 1}

logs: "./../logs"

hyps:
  n_split: 5
  max_len:
    assamese: 256
  seeds:
    - 2023